version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: xml-apis:xml-apis
    versions:
    - ">= 2.a, < 3"
  - dependency-name: org.n52.arctic-sea:svalbard-xmlstream
    versions:
    - 8.1.0
  - dependency-name: org.n52.arctic-sea:svalbard-xmlbeans
    versions:
    - 8.1.0
  - dependency-name: org.n52.arctic-sea:svalbard-json
    versions:
    - 8.1.0
  - dependency-name: org.n52.arctic-sea:svalbard-json-common
    versions:
    - 8.1.0
  - dependency-name: org.n52.arctic-sea:svalbard-exi
    versions:
    - 8.1.0
  - dependency-name: org.n52.arctic-sea:svalbard
    versions:
    - 8.1.0
  - dependency-name: org.n52.arctic-sea:svalbard-odata
    versions:
    - 8.1.0
  - dependency-name: org.n52.arctic-sea:shetland:tests
    versions:
    - 8.1.0
  - dependency-name: org.n52.arctic-sea:shetland
    versions:
    - 8.1.0
  - dependency-name: org.n52.arctic-sea:janmayen
    versions:
    - 8.1.0
  - dependency-name: org.n52.arctic-sea:faroe-json
    versions:
    - 8.1.0
  - dependency-name: org.n52.arctic-sea:faroe-annotations
    versions:
    - 8.1.0
  - dependency-name: org.n52.arctic-sea:faroe-utils
    versions:
    - 8.1.0
  - dependency-name: org.n52.arctic-sea:faroe
    versions:
    - 8.1.0
  - dependency-name: org.n52.arctic-sea:iceland-statistics-geolocation
    versions:
    - 8.1.0
  - dependency-name: org.n52.arctic-sea:iceland-statistics
    versions:
    - 8.1.0
  - dependency-name: org.n52.arctic-sea:iceland:tests
    versions:
    - 8.1.0
  - dependency-name: org.n52.arctic-sea:iceland
    versions:
    - 8.1.0
  - dependency-name: org.apache.xmlbeans:xmlbeans
    versions:
    - 5.1.0
